server {
    listen 80;

    location /api/auth {
        proxy_pass http://medishift-auth-service:3001;
    }

    location /api/staff {
        proxy_pass http://medishift-staff-service:3002;
    }

    location /api/departments {
        proxy_pass http://medishift-staff-service:3002;
    }

    location /api/shifts {
        proxy_pass http://medishift-shift-service:3003;
    }

    location /api/leaves {
        proxy_pass http://medishift-leave-service:3004;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
